quarkus.package.type=uber-jar

mp.jwt.verify.publickey.location=${ISSUER_PUBLIC_KEY}
mp.jwt.verify.issuer=${ISSUER}
smallrye.jwt.sign.key.location=${ISSUER_PRIVATE_KEY}

quarkus.http.port=${REST_SERVER_PORT}
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,PUT,POST,DELETE
quarkus.http.cors.headers=Access-Control-Allow-Origin, Referrer-Policy

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.reactive.url=postgresql://${DB_HOST:localhost}:${DB_HOST_PORT}/${DB}

#quarkus.http.root-path=/api

quarkus.oidc.auth-server-url=https://localhost:8080/oauth2/default
#quarkus.oidc.client-id=232318575426207747@semantyca
quarkus.oidc.client-id=233193190939817725@semantyca
#quarkus.oidc.credentials.secret=5mR65E2gLAT7zlqe8jtjG2fOaZ7SZQ50ckaCI8IPBxnrVV13vUSdPLYb3lig8oLX
quarkus.oidc.application-type=web_app



quarkus.http.auth.proactive=true

quarkus.grpc.server.enable-reflection-service=true
quarkus.grpc.server.use-separate-server=false

quarkus.log.category.grpc.level=DEBUG
io.grpc.netty.Utils=SEVERE

quarkus.log.level=DEBUG
# quarkus.log.level=ERROR
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
quarkus.log.console.color=true
quarkus.log.console.level=DEBUG
quarkus.log.file.enable=true
quarkus.log.file.path=/tmp/trace.log
quarkus.log.console.json=false

mailer.api.key=${MAILER_API_KEY}
mailer.sender=${MAIL_SENDER}

telegram.token=${TELEGRAM_TOKEN}
telegram.chatId=${TELEGRAM_CHAT_ID}


quarkus.swagger-ui.always-include=false

quarkus.log.category."io.smallrye.mutiny".level=DEBUG

#http requests
quarkus.log.category."io.undertow".level=DEBUG
quarkus.log.category."javax.net.ssl".level=DEBUG

#jwt
quarkus.log.category."io.quarkus.smallrye.jwt".level=DEBUG
quarkus.log.category."io.undertow.access-log".level=DEBUG

quarkus.log.category."io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator".level=TRACE
quarkus.log.category."io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator".min-level=TRACE


