quarkus.package.type=uber-jar

#database
quarkus.datasource.db-kind=postgresql

#cors
quarkus.http.cors=true
quarkus.http.cors.headers=Accept,Authorization,Content-Type,Origin
quarkus.http.cors.exposed-headers=Authorization,Link

#oidc
quarkus.oidc.application-type=web_app
quarkus.oidc.authentication.redirect-path=/
quarkus.oidc.roles.source=accesstoken
quarkus.oidc.roles.role-claim-path=realm_access/roles
quarkus.oidc.roles.role-claim-separator=,

#grpc
quarkus.grpc.server.enable-reflection-service=true
quarkus.grpc.server.use-separate-server=false
quarkus.log.category.grpc.level=DEBUG
io.grpc.netty.Utils=SEVERE

#openapi
quarkus.swagger-ui.always-include=false


