quarkus.package.type=uber-jar

mp.jwt.verify.publickey.location=${ISSUER_PUBLIC_KEY}
mp.jwt.verify.issuer=${ISSUER}

#jandex
#quarkus.index-dependency.kneo.classifier=io.kneo.core.model.SimpleReferenceEntity


#http
quarkus.http.port=${REST_SERVER_PORT}
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,PUT,POST,DELETE
quarkus.http.cors.headers=Access-Control-Allow-Origin, Referrer-Policy

#database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.reactive.url=postgresql://${DB_HOST:localhost}:${DB_HOST_PORT}/${DB}

#auth
#quarkus.oidc.application-type=web-app
#quarkus.oidc.application-type=hybrid
quarkus.oidc.application-type=service
quarkus.oidc.auth-server-url=${OIDC_SERVER}
quarkus.oidc.client-id=${OIDC_CLIENT_ID}
quarkus.oidc.credentials.secret=${OIDC_SECRET}
quarkus.oidc.authentication.redirect-path=/
#quarkus.oidc.roles.source=accesstoken
#quarkus.oidc.roles.role-claim-path=realm_access/roles
#quarkus.oidc.roles.role-claim-separator=,


#quarkus.oidc.authentication.restore-path-after-redirect=true
quarkus.oidc.tls.trust-store-file=${OIDC_TRUST_STORE}
quarkus.oidc.tls.trust-store-password=${OIDC_TRUST_STORE_PWD}


#grpc
quarkus.grpc.server.enable-reflection-service=true
quarkus.grpc.server.use-separate-server=false
quarkus.log.category.grpc.level=DEBUG
io.grpc.netty.Utils=SEVERE

#log
#quarkus.log.level=DEBUG
#quarkus.log.level=ERROR
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
#quarkus.log.console.color=true
#quarkus.log.console.level=DEBUG
quarkus.log.file.enable=true
quarkus.log.file.path=/tmp/trace.log
quarkus.log.console.json=false
#quarkus.log.category."io.smallrye.mutiny".level=DEBUG
#quarkus.log.category."io.undertow".level=DEBUG
#quarkus.log.category."javax.net.ssl".level=DEBUG
#quarkus.log.category."io.quarkus.smallrye.jwt".level=DEBUG
#quarkus.log.category."io.undertow.access-log".level=DEBUG
quarkus.log.category."io.quarkus.security".level=DEBUG
quarkus.log.category."io.quarkus.oidc".level=DEBUG



#mail
mailer.api.key=${MAILER_API_KEY}
mailer.sender=${MAIL_SENDER}

#telegramm
telegram.token=${TELEGRAM_TOKEN}
telegram.chatId=${TELEGRAM_CHAT_ID}

#openapi
quarkus.swagger-ui.always-include=false


